estimator:
  - name: exng-classifier
    params: {}

data:
  filepath: ./train_classification.csv

datatest:
  filepath: ./test_classification_students_fix.csv

metrics:
  - name: accuracy score
    params: {}
  - name: f1 score
    params: 
      average: 'micro'
  - name: precision score
    params: 
      average: 'macro'
  - name: recall score
    params: 
      average: 'macro'

search:
  jobs: -1
  grid:
    - name: random-forest-classifier
      params:
        max_features: ["auto", "sqrt", "log2", null, 20, 30, 40, 50, 60]
        max_depth: [null, 2, 4, 8, 18, 32, 64, 128, 256]
        n_estimators: [2, 4, 8, 16, 32, 64, 128, 256, 512]

export:
  output_dir: ./models

predexport:
  output_dir: ./predictions

reports:
  dir: ./reports